spring:
  datasource:
    url: jdbc:h2:mem:chatlive;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration-h2

app:
  email:
    enabled: false

logging:
  level:
    org.springframework.jdbc.core: INFO
